
export const TABLE_TEST_CURRICULUM_DATA = [
  {
    "cid": 40,
    "name": "Analiza convexa",
    "fid": 2,
    "year": 2,
    "teacher": "francespergola",
    "semester": 3,
    "maxstudents": 169,
    "priority": 2,
    "grade": 5,
    "credits": 3,
  },
  {
    "cid": 43,
    "name": "Modelare matematica",
    "fid": 2,
    "year": 2,
    "teacher": "johnschmid",
    "semester": 4,
    "maxstudents": 205,
    "priority": 1,
    "grade": 9,
    "credits": 4,
  },
  {
    "cid": 44,
    "name": "Capitole speciale de ecuatii diferentiale",
    "fid": 2,
    "year": 2,
    "teacher": "duanemorris",
    "semester": 4,
    "maxstudents": 208,
    "priority": 2,
    "grade": 10,
    "credits": 3,
  },
  {
    "cid": 47,
    "name": "Capitole speciale de ecuatii diferentiale",
    "fid": 2,
    "year": 2,
    "teacher": "duanemorris",
    "semester": 4,
    "maxstudents": 208,
    "priority": 2,
    "grade": 10,
    "credits": 3,
  },
  {
    "cid": 48,
    "name": "Capitole speciale de ecuatii diferentiale",
    "fid": 2,
    "year": 2,
    "teacher": "duanemorris",
    "semester": 4,
    "maxstudents": 208,
    "priority": 2,
    "grade": 10,
    "credits": 3,
  },
  {
    "cid": 49,
    "name": "Capitole speciale de ecuatii diferentiale",
    "fid": 2,
    "year": 2,
    "teacher": "duanemorris",
    "semester": 4,
    "maxstudents": 208,
    "priority": 2,
    "grade": 10,
    "credits": 3,
  },
]


export const TABLE_TEST_CURRICULUM_DATA_AFTER = [
  {
    "cid": 44,
    "name": "Cnvsbvisdbnjkfnbkfndrentiale",
    "fid": 2,
    "year": 2,
    "teacher": "duanemorris",
    "semester": 4,
    "maxstudents": 208,
    "priority": 2,
    "grade": 10,
    "credits": 3,
  },
]
